version: '3.8'

services:
  chatbotinfocitas:
    image: alexfer/chatbotinfocitas:1.0.0
    container_name: chatbotinfocitas_spring
    environment:
      - SPRING_DATA_MONGODB_HOST=chatbotinfocitas_mongo
      - SPRING_DATA_MONGODB_USERNAME=changetheusername
      - SPRING_DATA_MONGODB_PASSWORD=changethepass
      - SPRING_DATA_MONGODB_DATABASE=chatbotinfocitas
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    ports:
      - "8080:8080"
    networks:
      - chatbotinfocitas_network
networks:
  chatbotinfocitas_network:
    external: true